/**
 * Canonical analytics event names used by all clients.
 */
export const ANALYTICS_EVENTS = {
  FLASHCARD_FLIP: 'flashcard_flip',
  RECOGNITION_FEEDBACK_SUBMIT: 'recognition_feedback_submit',
  LEARNING_SESSION_COMPLETE: 'learning_session_complete',
  TOPIC_ENTER: 'topic_enter',
  TOPIC_EXIT: 'topic_exit',
  RECOGNITION_RESULT: 'recognition_result',
  CORRECTION_SUBMIT: 'correction_submit',
} as const;

export type AnalyticsEventName =
  (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];

export interface AnalyticsEventCommonPayload {
  /**
   * Role of the current user; typically learner/teacher/admin.
   */
  user_role: string;
  /**
   * Taxonomy id to support metrics slicing by species/topic.
   */
  taxon_id: string;
  /**
   * Session id generated by client or auth layer.
   */
  session_id: string;
  /**
   * ML model version serving recognition/feedback.
   */
  model_version: string;
  /**
   * Event generation timestamp.
   */
  event_ts: string;
}

export type AnalyticsEventPayload = AnalyticsEventCommonPayload &
  Record<string, string | number | boolean | null | undefined>;

export interface AnalyticsEvent {
  event_name: AnalyticsEventName;
  payload: AnalyticsEventPayload;
}
